SELECT B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, 
TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') CREATED_DATE
    FROM USED_GOODS_REPLY R
        INNER JOIN USED_GOODS_BOARD B
        ON  R.BOARD_ID = B.BOARD_ID 
    WHERE TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') LIKE '2022-10%'
    ORDER BY R.CREATED_DATE, B.TITLE ;